# values for helm deployment
replicaCount: 1
configmap:
  data:
    NODE_ENV: production

secrets:
    DATABASE_URL: ENC[AES256_GCM,data:LDf7cebi0TvuewFiT/RESrz7QExvS7ig60NuoUy47Ttmvj+M5U3IEB0YxTIEc141,iv:c8nGvYJ/6RRGX7CLGptAh30FsP8kfT4RtkZNfECC5XE=,tag:XXPbOqMhyv312DRkMBwGBw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-south-1:414085459896:key/fd131b5c-7276-4a20-acff-e5dbcfe9abfa
          created_at: "2022-01-03T05:09:50Z"
          enc: AQICAHiEL1x04pXTd3hPBnHHBjoa88PkHkd/VaziWRMTZ+NuMgHRfU0AL5s0emAmHRqAIcdFAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMe7fk1Ps5r56bDUB9AgEQgDs1EJCwbsHfnjZ6hqkkDBA7qWOGDIFtSZI/xlUAXiyD1dWsu1sQOJ+akDf0+iNmyoC2sjl4Kk5Q2iwDJg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-03T05:09:51Z"
    mac: ENC[AES256_GCM,data:OQiENJ95Cytd1uyMUyiQxLMsj8PYTPtTtOMt0AHmAgJ/CPhwQD+4QD0TfLJV4Uy1o+gAayXYUZu3VfuPZKmGU4v+8Gaz3KV6X0R48U435lMbyM1hYkY93r6kS8KwCRZ8H8OxAN6wv+LbN16qzGZnIKz4K688PPD0qDoDSPL9TCs=,iv:pHbxNe1/DBbo/ma1yMAtoa5QOV3Y7olYOxHboXusSOg=,tag:b2TnX9GLUsrvUeshiUwcIQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1

creation_rules:
  - kms: 'arn:aws:kms:ap-south-1:414085459896:key/fd131b5c-7276-4a20-acff-e5dbcfe9abfa'
    aws_profile: ''

number_of_jobs: 3
jobsEnabled: true
jobnamecron:
  job1: "* * * * *"
  job2: "*/2 * * * *"
  job3: "*/3 * * * *"
imagePullSecrets:
  - name: ap-south-1-ecr-registry
selectorLabels: "cs-jobs-poc"
labels: "cs-jobs-poc"
serviceAccountCreate: false
serviceAccountname: "default"
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
serviceEnabled: true
serviceType: 'ClusterIP'
service:
  enabled: true
  type: "ClusterIP"
  port: 8001
  targetPort: 8001
  name: http
livenessProbeEnabled: false
livenessProbe:
  enabled: false
  values:
    httpGet:
      path: ''
      port: http
readinessProbeEnabled: false
readinessProbe:
  enabled: false
  values:
    httpGet:
      path: ''
      port: http
resources: {}
autoscalingEnabled: false
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector:
  env: staging
tolerations: []
affinity: {}
imageRepository: '414085459896.dkr.ecr.ap-south-1.amazonaws.com/cs/jobs-poc'
imagePullPolicy: Always
imageTag: 'cmdev-c730d4'
imagePullSecrets:
  - name: ap-south-1-ecr-registry
ingressEnabled: false
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    ingress.kubernetes.io/force-ssl-redirect: 'true'
  tls:
    - secretName: ''
      hosts:
        - ''
hosts:
  - host: "abc.com"
    paths:
      - path: /
        pathType: Prefix