apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crm-charts.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crm-charts.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscalingEnabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "crm-charts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "crm-charts.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "crm-charts.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "414085459896.dkr.ecr.ap-south-1.amazonaws.com/cs/jobs-poc:cmdev-c730d4"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap
          {{- if .Values.serviceEnabled }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- end }}
          {{- if .Values.livenessProbeEnabled }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe.values | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbeEnabled }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe.values | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
