{{- if .Values.serviceAccountCreate }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "crm-charts.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crm-charts.labels" . | nindent 4 }}
  # {{- with .Values.serviceAccount.annotations }}
  # annotations:
  #   {{- toYaml . | nindent 4 }}
  # {{- end }}
{{- end }}
