
apiVersion: v1
kind: Service
metadata:
  name: {{ include "crm-charts.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crm-charts.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector: {{- include "crm-charts.selectorLabels" . | nindent 4 }}